### ISSUE TITLE
Remove snkmail.com and sneakemail.com

### ISSUE THREAD

**Issue by ryancdotorg** [FGRibreau/mailchecker#139]
Was previously requested in #108.

> Please remove snkmail.com. Although it started out as a disposable email service (sneakemail.com), snkmail.com is a paid-subscription service for generating long-lived unique email addresses for different purposes.
>
> Emails to the generated address is forwarded to the subscriber with the email tagged so that he knows which email it was sent to, and with the From address altered so that replies go back via snkmail servers and to the original sender. So this is really a service for identifying spam from websites, and not for generating disposable emails.

While Sneakemail bills itself as a "disposible email address" service, the addresses do not expire, they are valid until the user deletes them. Most people only delete the addresses if unsubscribe fails.

The idea is that rather than trying to filter spam (generally people whitelist everything coming through sneakemail), you have have one email address per sender. If a sender turns out to be bad (or they get hacked), you just turn that address off.

**Comment by terado** [comment]
Why on earth hasn't this been done yet! Sneakemail is an entirely legitimate service. This library is very questionable when it is tagging legitimate filtering services as spam.

**Comment by FGRibreau** [comment]
@ryancdotorg could you please open a PR for it?

**Comment by ryancdotorg** [comment]
Done

**Comment by terado** [comment]
Hi. Thanks for updating this ticket/work. I've just had a look through the latest list.json, I still see some instances remaining:
sneakemail.com Line 53
snkmail.com Line 53

I've not run the code, but these appear to be active triggers and presumably also need removing.

Many thanks!

**Comment by FGRibreau** [comment]
I will accept a pr for this thx

**Comment by ryancdotorg** [comment]
Please see PR #150
